SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart { get; }
        public CartSummaryViewComponent(Cart cartSerivce)
        {
            cart = cartSerivce;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }

    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

SportsStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Infrastructure;
using SportsStore.Models;
using SportsStore.Models.ViewModels;
using System.Linq;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;

        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>

    <form id="@Model.ProductID" asp-action="AddToCart"
    asp-controller="Cart" method="post">
    <input type="hidden" asp-for="ProductID"/>
    <input type="hidden" name="returnUrl"
        value="@ViewContext.HttpContext.Request.PathAndQuery()" />
    <span class="card-text p-1">@Model.Description
    <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right" >
        Add to cart</button>
        </span>
</form>
</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" asp-href-include="~/lib/twitter-bootstrap/**/*.min.css"
        asp-href-exclude="**/*-reboot*, **/*-grid*" />
	<link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
	<title>SportsStore</title>
</head>
<body>
	<div class="navbar navbar-inverse bg-inverse" role="navigation">
		<div class="row">
			<a class="col navbar-brand" href="#">Sports Store</a>
			<div class="col-4 text-right">
				@await Component.InvokeAsync("CartSummary")
			</div>
		</div>
	</div>
	<div class="row m-1 p-1">
		<div id="categories" class="col-3">
			@await Component.InvokeAsync("NavigationMenu") 
		</div>
		<div class="col-9">
			@RenderBody()
		</div>
	</div>
</body>
</html>